model: PointNet
device: cuda
dataset_dir: ../../data/blobs_full
dataset_file: ../../data/labels_three.csv
dataset_min_size: null
dataset_max_size: null
batch_size: 64
no_workers: 8
epochs: 2
weight_decay: 1e-4
lr: 1e-3
accum_iter: 4
