model: MinkLoc3Dv2
device: cpu
dataset_dir: ../data/blobs_pca_kmeans_2000_1_2
dataset_file: ../data/train.csv
dataset_min_size: null
dataset_max_size: null
batch_size: 64
no_workers: 8
epochs: 50
weight_decay: 1e-4
lr: 1e-3
accum_iter: 4
