model: TransLoc3D
device: cuda
dataset_dir: ../data/blobs_full
dataset_file: ../data/train.csv
dataset_sample_size: 2000
batch_size: 64
no_workers: 8
epochs: 100
weight_decay: 1e-4
lr: 1e-3
accum_iter: 4
