services:
  app:
    image: jkarolczak/ligand-deploy:st-1.37.1
    volumes:
      - "../:/app:rw"
      - "${PWD}/model.pt:/app/src/deploy/model.pt"
    working_dir: /app
    tty: true
    stdin_open: true
    entrypoint: streamlit run /app/src/deploy/app.py
    environment:
      - MKL_THREADING_LAYER=1
      - STREAMLIT_SERVER_HEADLESS=true
      - STREAMLIT_SERVER_CORS_ORIGINS=https://ligands.cs.put.poznan.pl,https://ligands.xyz
    ports:
      - "8501:8501"
    restart: always

  api:
    image: jkarolczak/ligand-deploy:flask-3.0.3
    volumes:
      - "../:/app:rw"
      - "${PWD}/model.pt:/app/src/deploy/model.pt"
    working_dir: /app
    tty: true
    stdin_open: true
    entrypoint: python3 api.py
    environment:
      - MKL_THREADING_LAYER=1
    ports:
      - "5000:5000"
    restart: always

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ${PWD}/docker/nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt:/etc/letsencrypt
    restart: always
    depends_on:
      - app
      - api
