services:
  streamlit:
    image: jkarolczak/ligand-deploy:lite
    volumes:
      - "../:/app:rw"
      - "${PWD}/model.pt:/app/src/deploy/model.pt"
    working_dir: /app
    tty: true
    stdin_open: true
    command: >
      bash -c "pip install streamlit==1.37.1 
      && streamlit run /app/src/deploy/app.py --server.port 8501 --browser.gatherUsageStats=false --theme.base="light" --server.enableCORS=false --server.enableXsrfProtection=false"
    environment:
      - MKL_THREADING_LAYER=1
      - STREAMLIT_SERVER_HEADLESS=true
      - STREAMLIT_SERVER_CORS_ORIGINS=https://ligands.cs.put.poznan.pl,https://ligands.xyz
    ports:
      - "8501:8501"

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ${PWD}/docker/nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt:/etc/letsencrypt
    depends_on:
      - streamlit

