version: '3'

services:
  minkowski_cpu:
    build:
      context: ..
      dockerfile: docker/DockerfileCPU
    volumes:
      - "../:/app:rw"
      - "${DATA_PATH}:/app/data:rw"
    working_dir: /app/scripts
    tty: true
    stdin_open: true
    network_mode: "host"
    entrypoint: /bin/bash
    environment:
      MKL_THREADING_LAYER: 1
