services:
  streamlit:
    image: jkarolczak/ligand-deploy:lite
    volumes:
      - "../:/app:rw"
      - "${PWD}/model.pt:/app/src/deploy/model.pt"
    working_dir: /app
    tty: true
    stdin_open: true
    entrypoint: streamlit run /app/src/deploy/app.py --server.port 8501
    environment:
      - MKL_THREADING_LAYER=1
      - STREAMLIT_SERVER_HEADLESS=true
    ports:
      - "8501:8501"

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ${PWD}/docker/nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt:/etc/letsencrypt
    depends_on:
      - streamlit

